TRACKS = {
    1: {"name": "Crazy Straights", "color": "Red", "country": "France", "complexity": 6},
    2: {"name": "Bank Job", "color": "Red", "country": "Japan", "complexity": 4},
    3: {"name": "Tubular Hell", "color": "Blue", "country": "Japan", "complexity": 7},
    4: {"name": "Curbed Heights", "color": "Red", "country": "France", "complexity": 6},
    5: {"name": "Flying Finish", "color": "Blue", "country": "Italy", "complexity": 8},
    6: {"name": "Secret Six", "color": "Blue", "country": "Spain", "complexity": 7},
    7: {"name": "The Sandwinder", "color": "Green", "country": "Spain", "complexity": 8},
    8: {"name": "Roughdust Flats", "color": "Green", "country": "Spain", "complexity": 6},
    9: {"name": "The Loopback", "color": "Blue", "country": "United Kingdom", "complexity": 7},
    10: {"name": "Intersector", "color": "Red", "country": "United Kingdom", "complexity": 7},
    11: {"name": "Rise N' Fall", "color": "Blue", "country": "Spain", "complexity": 6},
    12: {"name": "Wide Wall Chase", "color": "Red", "country": "Spain", "complexity": 5},
    13: {"name": "Curb City Circuit", "color": "Red", "country": "USA", "complexity": 5},
    14: {"name": "Waterfront Dash", "color": "Red", "country": "Italy", "complexity": 9},
    15: {"name": "Freefall Freeway", "color": "Blue", "country": "Spain", "complexity": 6},
    16: {"name": "High Roller", "color": "Red", "country": "Germany", "complexity": 7},
    17: {"name": "Highfly Clearway", "color": "Green", "country": "Japan", "complexity": 9},
    18: {"name": "Helipad Heights", "color": "Blue", "country": "USA", "complexity": 6},
    19: {"name": "Sunken Sights", "color": "Green", "country": "Spain", "complexity": 6},
    20: {"name": "Dust Buster", "color": "Green", "country": "Japan", "complexity": 4},
    21: {"name": "Twinloop Circuit", "color": "Blue", "country": "Germany", "complexity": 8},
    22: {"name": "Snakestorm", "color": "Blue", "country": "Germany", "complexity": 6},
    23: {"name": "Skytop Speed Circuit", "color": "Red", "country": "USA", "complexity": 4},
    24: {"name": "The Chronozone", "color": "Red", "country": "France", "complexity": 4},
}
CARS = {
    1: {"name": "Mean Streak", "group": "Speed Demons"},
    2: {"name": "The Hustler", "group": "Wild Wheels"},
    3: {"name": "Twin Eagle", "group": "Aero Blasters"},
    4: {"name": "Sky Hawk", "group": "Aero Blasters"},
    5: {"name": "The Phantom", "group": "Speed Demons"},
    6: {"name": "Road Hog", "group": "Wild Wheels"},
    7: {"name": "Dune Rat", "group": "Wild Wheels"},
    8: {"name": "Nitro Lightnin'", "group": "Speed Demons"},
    9: {"name": "Alley Cat", "group": "Speed Demons"},
    10: {"name": "Sand Shark", "group": "Wild Wheels"},
    11: {"name": "The Brute", "group": "Wild Wheels"},
    12: {"name": "Wild Dart", "group": "Aero Blasters"},
    13: {"name": "Raging Bull", "group": "Wild Wheels"},
    14: {"name": "Flying Mantis", "group": "Aero Blasters"},
    15: {"name": "Stunt Monkey", "group": "Aero Blasters"},
    16: {"name": "Inferno", "group": "Speed Demons"},
    17: {"name": "Forkster", "group": "Team Specials"},
    18: {"name": "Wormsmobile", "group": "Team Specials"},
    19: {"name": "Formula 17", "group": "Team Specials"},
    20: {"name": "Team Machine", "group": "Team Specials"},
}
SETUP_MD5 = "d3c9afeda52418470db56c2ed2d90a35"
